# 2).Write a program to store six marks in a list entered by the user and sort them in descending order.
marks=[]
m1=int(input("Enter marks: "))
marks.append(m1)
m2=int(input("Enter marks: "))
marks.append(m2)
m3=int(input("Enter marks: "))
marks.append(m3)
m4=int(input("Enter marks: "))
marks.append(m4)
m5=int(input("Enter marks: "))
marks.append(m5)
m6=int(input("Enter marks: "))
marks.append(m6)
s=sorted(marks)
print(s)
